
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "JCertifBO": "../../app",
  "Ext": "../../ext/src",
  "Ext.rtl.EventObjectImpl": "../../ext/src/rtl/EventObject.js",
  "Ext.ux.GroupTreeChunker": "../../ext/src/ux/GroupTabPanel.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "JCertifBO.model.SessionStatus": [],
  "JCertifBO.view.room.Grid": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "JCertifBO.view.AdminOptionsList": [],
  "JCertifBO.store.Titles": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "JCertifBO.controller.SponsorController": [],
  "JCertifBO.controller.SpeakerController": [],
  "JCertifBO.view.Viewer": [],
  "Ext.ux.DataView.DragSelector": [],
  "JCertifBO.model.User": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "JCertifBO.controller.ReferentielController": [],
  "JCertifBO.controller.SiteController": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "JCertifBO.view.speaker.Grid": [],
  "JCertifBO.view.Viewport": [],
  "JCertifBO.view.referentiel.Add": [],
  "Ext.ux.CheckColumn": [],
  "Ext.ux.PreviewPlugin": [],
  "JCertifBO.controller.AdminOptionsController": [],
  "JCertifBO.store.Sessions": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [],
  "JCertifBO.store.SponsorLevels": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "Ext.ux.event.Recorder": [],
  "JCertifBO.view.session.Add": [],
  "JCertifBO.model.Site": [],
  "Ext.ux.ajax.SimManager": [],
  "JCertifBO.model.Session": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Ext.ux.TabScrollerMenu": [],
  "JCertifBO.model.Title": [],
  "Ext.ux.IFrame": [],
  "JCertifBO.model.Speaker": [],
  "JCertifBO.view.Login": [],
  "Ext.ux.form.SearchField": [],
  "JCertifBO.view.AppHeader": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Ext.ux.TreePicker": [],
  "JCertifBO.view.sponsor.Add": [],
  "JCertifBO.view.participant.Grid": [],
  "JCertifBO.store.Categories": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "JCertifBO.controller.LoginController": [],
  "Ext.ux.BoxReorderer": [],
  "JCertifBO.store.SessionStatuses": [],
  "JCertifBO.controller.ParticipantController": [],
  "Ext.ux.grid.filter.Filter": [],
  "JCertifBO.store.Speakers": [],
  "JCertifBO.view.sponsor.Grid": [],
  "JCertifBO.view.speaker.Add": [],
  "Ext.ux.FieldReplicator": [],
  "JCertifBO.model.Room": [],
  "JCertifBO.model.Category": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "JCertifBO.view.site.Add": [],
  "JCertifBO.controller.RoomController": [],
  "JCertifBO.view.participant.Add": [],
  "JCertifBO.model.SponsorLevel": [],
  "Ext.ux.GMapPanel": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Ext.ux.GroupTreeChunker": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [],
  "JCertifBO.store.Sites": [],
  "JCertifBO.store.AdminOptions": [],
  "JCertifBO.model.Referentiel": [],
  "Ext.ux.DataView.Animated": [],
  "JCertifBO.controller.HomeController": [],
  "JCertifBO.view.room.Add": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "JCertifBO.model.AdminOption": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Player": [],
  "JCertifBO.model.Participant": [],
  "JCertifBO.store.Users": [],
  "JCertifBO.view.option.Show": [],
  "JCertifBO.view.Home": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "JCertifBO.view.referentiel.Grid": [],
  "JCertifBO.store.Rooms": [],
  "JCertifBO.view.session.Grid": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [],
  "JCertifBO.controller.SessionController": [],
  "JCertifBO.view.site.Grid": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "JCertifBO.model.Sponsor": [],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": []
});
Ext.ClassManager.addNameAliasMappings({
  "JCertifBO.model.SessionStatus": [],
  "JCertifBO.view.room.Grid": [
    "widget.roomgrid"
  ],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "JCertifBO.view.AdminOptionsList": [
    "widget.adminoptionslist"
  ],
  "JCertifBO.store.Titles": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "JCertifBO.controller.SponsorController": [],
  "JCertifBO.controller.SpeakerController": [],
  "JCertifBO.view.Viewer": [
    "widget.viewer"
  ],
  "Ext.ux.DataView.DragSelector": [],
  "JCertifBO.model.User": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "JCertifBO.controller.ReferentielController": [],
  "JCertifBO.controller.SiteController": [],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "JCertifBO.view.speaker.Grid": [
    "widget.speakergrid"
  ],
  "JCertifBO.view.Viewport": [],
  "JCertifBO.view.referentiel.Add": [
    "widget.referentieladd"
  ],
  "Ext.ux.CheckColumn": [
    "widget.checkcolumn"
  ],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "JCertifBO.controller.AdminOptionsController": [],
  "JCertifBO.store.Sessions": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "JCertifBO.store.SponsorLevels": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "Ext.ux.event.Recorder": [],
  "JCertifBO.view.session.Add": [
    "widget.sessionadd"
  ],
  "JCertifBO.model.Site": [],
  "Ext.ux.ajax.SimManager": [],
  "JCertifBO.model.Session": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "JCertifBO.model.Title": [],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "JCertifBO.model.Speaker": [],
  "JCertifBO.view.Login": [
    "widget.login"
  ],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "JCertifBO.view.AppHeader": [
    "widget.appheader"
  ],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "JCertifBO.view.sponsor.Add": [
    "widget.sponsoradd"
  ],
  "JCertifBO.view.participant.Grid": [
    "widget.participantgrid"
  ],
  "JCertifBO.store.Categories": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "JCertifBO.controller.LoginController": [],
  "Ext.ux.BoxReorderer": [],
  "JCertifBO.store.SessionStatuses": [],
  "JCertifBO.controller.ParticipantController": [],
  "Ext.ux.grid.filter.Filter": [],
  "JCertifBO.store.Speakers": [],
  "JCertifBO.view.sponsor.Grid": [
    "widget.sponsorgrid"
  ],
  "JCertifBO.view.speaker.Add": [
    "widget.speakeradd"
  ],
  "Ext.ux.FieldReplicator": [],
  "JCertifBO.model.Room": [],
  "JCertifBO.model.Category": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "JCertifBO.view.site.Add": [
    "widget.siteadd"
  ],
  "JCertifBO.controller.RoomController": [],
  "JCertifBO.view.participant.Add": [
    "widget.participantadd"
  ],
  "JCertifBO.model.SponsorLevel": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Ext.ux.GroupTreeChunker": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "JCertifBO.store.Sites": [],
  "JCertifBO.store.AdminOptions": [],
  "JCertifBO.model.Referentiel": [],
  "Ext.ux.DataView.Animated": [],
  "JCertifBO.controller.HomeController": [],
  "JCertifBO.view.room.Add": [
    "widget.roomadd"
  ],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "JCertifBO.model.AdminOption": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [
    "plugin.rowexpander"
  ],
  "Ext.ux.event.Player": [],
  "JCertifBO.model.Participant": [],
  "JCertifBO.store.Users": [],
  "JCertifBO.view.option.Show": [
    "widget.optionshow"
  ],
  "JCertifBO.view.Home": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "JCertifBO.view.referentiel.Grid": [
    "widget.referentielgrid"
  ],
  "JCertifBO.store.Rooms": [],
  "JCertifBO.view.session.Grid": [
    "widget.sessiongrid"
  ],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "JCertifBO.controller.SessionController": [],
  "JCertifBO.view.site.Grid": [
    "widget.sitegrid"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "JCertifBO.model.Sponsor": [],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ]
});
